server:
  port: 8080
  mode: "dev"
  host: "localhost"

mongodb:
  host: ${MONGODB_HOST}
  port: ${MONGODB_PORT}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  database: ${MONGODB_DATABASE}
  timeout: 10
  max_pool_size: 50
  min_pool_size: 5
  max_conn_idle_time: 300

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}
  pool_size: 20
  min_idle_conns: 5
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  max_retries: 3
  max_retry_backoff: 500
  min_retry_backoff: 300
  max_conn_pool_size: 100
  min_conn_pool_size: 10
  conn_pool_timeout: 6

logger:
  log_level: info
  file_log_name: "./storages/logs/app.log"
  max_backups: 10
  max_age: 3
  max_size: 5
  compress: true
