server:
  port: 8080
  mode: "dev"
  host: "localhost"

mongodb:
  host: ${MONGODB_HOST}
  port: ${MONGODB_PORT}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  database: ${MONGODB_DATABASE}
  timeout: 10
  max_pool_size: 50
  min_pool_size: 5
  max_conn_idle_time: 300

logger:
  log_level: info
  file_log_name: "./storages/logs/app.log"
  max_backups: 10
  max_age: 3
  max_size: 5
  compress: true
